version: "3.4"

services:
  api:
    container_name: nodeTs
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
  mysql:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dockerExample1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_PASSWORD: root1234
      PMA_USER: root
      PMA_PORT: 3360
      PMA_HOSTS: mysql